tools:
  update_function:
    signature: "update_function <update_type> [<function_name>] [<new_name>] [<new_type>]"
    docstring: >
      A tool for analyzing and updating code properties inside LLVM bitcode files.
      You can change the properties of a function, such as its type, name.

    arguments:
      - name: update_type
        type: string
        description: "The type of update to perform on the function: name, type"
        required: true
      - name: function_name
        type: string
        description: "The name of the function to update"
        required: true
      - name: new_name
        type: string
        description: "The new name for the function (if updating name)"
        required: false
      - name: new_type
        type: string
        description: "The path to new type definition file (written in C source code) to update function's type"
        required: false